name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [8.0, 7.4, 7.3, 7.2]
        os: [ubuntu-latest]

    name: php ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction

      - name: Start Rundeck docker container
        run: docker-compose up -d

      - name: Wait for docker container to finish building
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:4440/'
          interval: 5000
          timeout: 90000

      - name: Execute tests
        run: ./vendor/bin/phpunit